Repository sleddog/methods-spring-2020, pull requests merged in 2020-04, with the labels that each got.

#109 Group1 assignment4
  GROUPS.md
  services/ingredient-type/README.md
  services/ingredient-type/api.yml
Labels: assignment4

#104 www.okayestmagic8ball.com
  .gitignore
  services/witty-name/README.md
  services/witty-name/api.yaml
  services/witty-name/flaskapp.py
  services/witty-name/static/index.js
  services/witty-name/static/layout.css
  services/witty-name/templates/home.html
Labels: assignment5

#110 Mad lads
  services/mad-lads/README.md
  services/mad-lads/application.py
Labels: assignment5

#116 Update PANEL.md
  PANEL.md
Labels: Assignment 6

#115 Add question to panel.md
  PANEL.md
Labels: Assignment 6

#117 Added my panel questions
  PANEL.md
Labels: Assignment 6
