Repository sleddog/methods-spring-2020, pull requests merged in 2020-03, with the labels that each got.

#55 JasonBengtson-assignment2
  problems/kattis/quadrant/java/jasonBengtson/Quadrant.java
  problems/kattis/quadrant/java/jasonBengtson/Quadrant.md
Labels: assignment2

#50 Added solution and readme back
  problems/euler/num22-names-scores/ruby/DanielBachler/README.md
  problems/euler/num22-names-scores/ruby/DanielBachler/exampleRun.png
  problems/euler/num22-names-scores/ruby/DanielBachler/solution.rb
Labels: assignment2

#71 Jamie Winter Assignment 2
  problems/euler/multiplesOf3And5/java/jailarie/README.md
  problems/euler/multiplesOf3And5/java/jailarie/eulerProblemOne.java
Labels: assignment2

#52 Re-add faktor solution and readme for assignment 2
  problems/kattis/faktor/C++/cjyovich/README.md
  problems/kattis/faktor/C++/cjyovich/faktor.cpp
Labels: assignment2

#45 Assignment2 /Farismhg
  problems/euler/Smallest multiple/Java/Farismhg/Multiple.java
  problems/euler/Smallest multiple/Java/Farismhg/README.md
Labels: assignment2

#46 Wyatt Benson - Assignment 2
  problems/euler/README.md
  problems/euler/problem71/CPlusPlus/WyattBenson/README.md
  problems/euler/problem71/CPlusPlus/WyattBenson/prob71.cpp
Labels: assignment2

#65 Dzumpano assignment2
  problems/euler/pseudo-square-root/python/dzumpano/README.md
  problems/euler/pseudo-square-root/python/dzumpano/psr.c
Labels: assignment2

#49 Submitting Assignment 2 - Adam Saylor
  problems/kattis/A-New-Alphabet/java/sayloradm/README.md
  problems/kattis/A-New-Alphabet/java/sayloradm/newAlphabet.java
Labels: assignment2

#41 python file and readme
  problems/euler/num1-multof3and5-under1000/draft.txt
  problems/euler/num1-multof3and5-under1000/projecteulerproblem1.py
  problems/euler/problem-1-num1-multof3and5-under1000/.DS_Store
  problems/euler/problem-1-num1-multof3and5-under1000/python/.DS_Store
  problems/euler/problem-1-num1-multof3and5-under1000/python/GabeEwsuk/.DS_Store
  problems/euler/problem-1-num1-multof3and5-under1000/python/GabeEwsuk/README.md
  problems/euler/problem-1-num1-multof3and5-under1000/python/GabeEwsuk/projecteulerproblem1.py
Labels: assignment2

#73 assignment 2
  problems/euler/Multiples_of_3_and_5/python/MarnieRM/README.md
  problems/euler/Multiples_of_3_and_5/python/MarnieRM/main.py
Labels: assignment2

#59 Blake stanger assignment2
  ARTICLES.md
  favorite/BOOKS.md
  favorite/MOVIES.md
  favorite/NETFLIX.md
  new.txt
  problems/kattis/Cold-puter/python/BlakeStanger/Cold-puter.py
  problems/kattis/Cold-puter/python/BlakeStanger/README.txt
  problems/kattis/Cold-puter/python/BlakeStanger/cold-001.in
  problems/kattis/Cold-puter/python/BlakeStanger/cold-002.in
Labels: assignment2

#34 Assignment 2 submission
  .gitignore
  problems/kattis/NoDuplicates/python/Dmoayad/NoDuplicates.py
  problems/kattis/NoDuplicates/python/Dmoayad/README.md
  problems/kattis/NoDuplicates/python/Dmoayad/test_NoDuplicates.py
Labels: assignment2

#51 Logan Pappas Assignment2
  problems/euler/problem1/java/LoganPappas/Driver.java
  problems/euler/problem1/java/LoganPappas/README.md
Labels: assignment2

#42 Submission for assignment 2
  .gitignore
  problems/euler/problem4/java/connorludwig/README.md
  problems/euler/problem4/java/connorludwig/solution.java
Labels: assignment2

#66 Solved Homework 2
  problems/euler/15/java/IndustryMethodsTask2.java
  problems/euler/15/java/README.md
Labels: assignment2

#70 Groups for Assignments 4 & 5
  GROUPS.md
Labels: assignment4

#75 Adam Saylor Assignment 3
  problems/kattis/A-New-Alphabet/java/sayloradm/README.md
  problems/kattis/A-New-Alphabet/java/sayloradm/TestFinal.java
  problems/kattis/A-New-Alphabet/java/sayloradm/newAlphabet.java
Labels: assignment3

#84 Moayad assignment3
  problems/kattis/NoDuplicates/python/Dmoayad/README.md
  problems/kattis/NoDuplicates/python/Dmoayad/test_NoDuplicates.py
Labels: assignment3

#77 Added unit tests and updated README
  problems/euler/num22-names-scores/ruby/DanielBachler/README.md
  problems/euler/num22-names-scores/ruby/DanielBachler/solution.rb
  problems/euler/num22-names-scores/ruby/DanielBachler/test.rb
  problems/euler/num22-names-scores/ruby/DanielBachler/testsRunning.png
Labels: assignment3

#61 Add files via upload
  problems/kattis/SHell/Java/benbarn313/Main.java
  problems/kattis/SHell/Java/benbarn313/README.md.txt
Labels: assignment2

#81 LoganPappasAssignment3
  problems/euler/problem1/java/LoganPappas/Driver.java
  problems/euler/problem1/java/LoganPappas/MyUnitTest.java
  problems/euler/problem1/java/LoganPappas/README.md
Labels: assignment3

#78 Courtney Yovich assignment3
  problems/kattis/faktor/C++/cjyovich/README.md
  problems/kattis/faktor/C++/cjyovich/faktor.cpp
  problems/kattis/faktor/C++/cjyovich/test_faktor.cpp
Labels: assignment3

#92 Add files via upload
  services/Funkytown/README.md.txt
  services/Funkytown/api.yaml.txt
Labels: assignment4

#94 Group4 assignment4
  GROUPS.md
  services/witty-name/README.md
  services/witty-name/api.yaml
Labels: assignment4

#95 Mad lads
  GROUPS.md
  services/mad-lads/README.md
  services/mad-lads/application.py
  services/mad-lads/openapi.yaml
  services/mad-lads/package.json
Labels: assignment4

#99 Group 4 Assignment 4
  GROUPS.md
  problems/kattis/different/kotlin/sleddog/src/main/.main.kt.swp
  services/quaranteam/README.md
  services/quaranteam/api.yaml
Labels: assignment4

#100 ForOhFour-Assignment4
  GROUPS.md
  services/for-oh-four/README.md
  services/for-oh-four/api.yaml
Labels: assignment4
